apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: external-dns.dev.failk8s.com.0.8.0
  namespace: kapp-controller-packaging-global
spec:
  refName: external-dns.dev.failk8s.com
  version: 0.8.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/external-dns-package:0.8.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
