#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: #@ "{}.{}".format(data.values.repository.name,data.values.repository.domain)
spec:
  syncPeriod: 1m
  fetch:
    imgpkgBundle:
      image: #@ "{}/{}:{}".format(data.values.registry, data.values.repository.name, data.values.repository.version)
