apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: failk8s-repo.dev.failk8s.com
spec:
  syncPeriod: 1m
  fetch:
    imgpkgBundle:
      image: quay.io/failk8s/failk8s-repo:develop
