apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: trow-registry.dev.failk8s.com.0.0.0+develop
spec:
  refName: trow-registry.dev.failk8s.com
  version: 0.0.0+develop
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/trow-registry-package:develop
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
